# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "APSelect : Chasseur de voiture spécialisée youngtimers."
email: contact@apselect.fr
description: > # this means to ignore newlines until "baseurl:"
  Neko garde d'animaux (Lyon, Villeurbanne) vous propose de rendre visite à votre animal lors de vos vacances ou vos déplacements. Professionnelle et passionnée, je me déplace à votre domicile pour m'occuper de votre chien, chat ou NAC.
baseurl:  # the subpath of your site, e.g. /blog
url: "http://apselect.fr" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
default_locale: "fr"
markdown: kramdown
theme: minima
permalink: pretty
gems:
  - jekyll-feed
  - jekyll-minifier
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .sass-cache/
  - _site/